[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jenova"
version = "0.1.1"
dependencies = [
]

[project.scripts]
jenova_server = "jenova.server:main"
jenova_client = "jenova.client:main"

[tool.setuptools.packages.find]
where = ["src"]
